# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node.js 14.x
      uses: actions/checkout@v3
      with:
        node-version: '14.x'
    - uses: borales/actions-yarn@v3.0.0
      with:
        cmd: install
    - uses: borales/actions-yarn@v3.0.0
      with:
        cmd: build
    - uses: borales/actions-yarn@v3.0.0
      with:
        cmd: test
